version: '3'
services:
  node0:
    build:
      context: .
      dockerfile: Dockerfile.rbbc
    image: rbbc
    volumes:
      - ./peers.json:/rbbc/peers.json:ro
    command: ["-id", "0", "-peers", "/rbbc/peers.json", "-log", "Node0:2", "-log", "RBBC:4"]
  node1:
    build:
      context: .
      dockerfile: Dockerfile.rbbc
    image: rbbc
    volumes:
      - ./peers.json:/rbbc/peers.json:ro
    command: ["-id", "1", "-peers", "/rbbc/peers.json", "-log", "Node1:2", "-log", "RBBC:4"]
  node2:
    build:
      context: .
      dockerfile: Dockerfile.rbbc
    image: rbbc
    volumes:
      - ./peers.json:/rbbc/peers.json:ro
    command: ["-id", "2", "-peers", "/rbbc/peers.json", "-log", "Node2:2", "-log", "RBBC:4"]
  node3:
    build:
      context: .
      dockerfile: Dockerfile.rbbc
    image: rbbc
    volumes:
      - ./peers.json:/rbbc/peers.json:ro
    command: ["-id", "3", "-peers", "/rbbc/peers.json", "-log", "Node3:2", "-log", "RBBC:4"]
